### ISSUE TITLE
How to render paragraphs?

### ISSUE THREAD

**Issue by kkoomen** [headless-ninja/javascript#35]
I have been debugged the core code to try to render a single paragraph, but can't wrap my head around the correct way to render a single paragraph.... this is what I have:

```
        <DrupalPage
          url={pathname + search}
          mapper={{
            node__article: () => {
              return <p>node article!</p>;
            },
            paragraph__image_grid: () => {
              return <p>image grid!</p>;
            },
          }}
        />
```

I am viewing this on an article which is present in my url as: `/en/article/test` and the `node__article` is rendering, but the `paragraph__image_grid` is not rendering while it is present when I am fetching: `localhost:3000/hn?_format=hn&path=/en/article/test`, it gives me the following output:

```
{
  "data": {
    "config__menus": {},
    "d0a7765f-d8c0-46d8-967b-3475acd9ba55": {
      "__hn": {
        "view_modes": [
          "default"
        ],
        "entity": {
          "type": "node",
          "bundle": "article"
        },
        "url": "/en/articles/test",
        "status": 200
      },
      "nid": 3263
      ...
    },
    "284c4f89-bc0f-4055-af89-1aeddccb9266": {
      "__hn": {
        "view_modes": [
          "default"
        ],
        "entity": {
          "type": "paragraph",
          "bundle": "image_grid"
        }
      },
      "id": 2511,
      "uuid": "284c4f89-bc0f-4055-af89-1aeddccb9266"
      ...
    }
  }
}
```

If I am looking at ChupaChups then they have defined in the mapper paragraphs as well, such as:

```
<DrupalPage
  mapper={{
    paragraph__image_grid: () => ImageGrid,
  }}
/>
```

But this doesn't seem to work for me ..

Any ideas?

**Comment by ianwensink** [comment]
Hi there,

Thank you for trying out HN, and raising this question.

The important thing to know (which you couldn't know, due to lack of documentation) is that rendering stuff is nested, just like Drupal templates.

So, that you're article is rendering makes sense, since you are viewing a URL that will resolve to a node with the `article` bundle.

To know how you expect your paragraph to be rendered, I need to know how your Drupal is set up. Do you have a Paragraphs field on the article node?

If so, you'll need to nest the components just like Drupal templates would be nested. To make that more clear: the DrupalPage component is merely for rendering the top level of your Drupal site, so basically the Content Types. Inside a Content Type component (like your Article) you can render the node fields, such as title, images, and paragraph fields.

Your JSON should reflect that. It has a key
`"/en/articles/test": "d0a7765f-d8c0-46d8-967b-3475acd9ba55"` which is telling you that when a visitor goes to `"/en/articles/test"`, the entity with UUID` "d0a7765f-d8c0-46d8-967b-3475acd9ba55"` should be rendered. I assume your JSON then says:

    "d0a7765f-d8c0-46d8-967b-3475acd9ba55": {
        ...data...
       field_paragraphs: [
          {
              "target_uuid": "284c4f89-bc0f-4055-af89-1aeddccb9266"
          }
       ]
     }

This is assuming your paragraphs field is called `field_paragraphs`.

This makes `field_paragraphs` one of your Node's fields, just like title and image, and therefore it should be rendered just like a title and image: within the Node component.

So let me try to give you an example.

Your example:


    <DrupalPage
       url={pathname + search}
       mapper={{
         node__article: () => {
           return <p>node article!</p>;
         },
         paragraph__image_grid: () => {
           return <p>image grid!</p>;
          },
        }}
      />


Then becomes:

    <DrupalPage
      url={pathname + search}
      mapper={{
        node__article: ({ page }) => {
          return (
             <p>
                node article!
                 <EntityMapper
                   mapper={{
                      paragraph__image_grid: () => {
                        return <p>image grid!</p>;
                      }
                    }}
                    entities={page.FIELD_WHERE_PARAGRAPHS_ARE_IN}
                  />
               </p>
             ):
           },
        }}
      />



Or perhaps splitting it up into components makes it more clear:

      <DrupalPage
          url={pathname + search}
          mapper={{
            node__article: Article
          }}
        />


       const Article = ({ page }) => {
          return (
            <p>
               node article!
               <EntityMapper
                  mapper={{
                     paragraph__image_grid: ImageGridParagraph
                  }}
                  entities={page.FIELD_WHERE_PARAGRAPHS_ARE_IN}
                />
             </p>
          ):
       };

       const ImageGridParagraph = ({ entity }) => {
           return (
              <p>image grid!</p>
          );
      });


I hope this answers your question, otherwise I would need more information about your Drupal setup to correctly deliver you the examples for the React components.

**Comment by kkoomen** [comment]
@ianwensink Thank you very much for the detailed explanation! I already considered this option, but wasn't sure, compared to the example of ChupaChups, if that was an option or the way to go. This works indeed as expected and makes sense as well! Thanks! 👍

**Comment by ianwensink** [comment]
Hi Kim,

No problem, happy I could help out.

The development of this module is very active indeed, it's just that the core team as a whole is busy with finishing up another project. We scheduled to release a stable 1.0 version for both the Drupal module, JavaScript core module (hn) and the React implementation (hn-react) end of this summer.

We will publish a roadmap somewhere in July, so feel free to contact us with your thoughts once we have it. We are also scheduling a hackathon where we will build on the 1.0 release, so stay tuned for that as well.

A few things we think are necessary for a stable release are
- implementing context in entities (examples of context are language, whether you're logged in, geolocation) so we can invalidate entities in cache whenever the context changes;
- adding a way to define needed fields from within your components, very much like GraphQL does, so Drupal never sends unnecessary data and the React developer doesn't need a Drupal developer to use an existing field in a component;
- making the visual connection between the front end and back end more smoothly by for instance adding inline editing, previews in Drupal, draft modes in the front end, et cetera.
- **WRITING DOCUMENTATION** ;-)
- add ways in Drupal to support big piping and make decorators for entities (as an addition to the HnEntityManagerPlugin, since you can only have one of those per entity).

Thanks for your positive words, and please stay tuned! I will close this now, but feel free to reopen of you are having more questions.

**Comment by kkoomen** [comment]
@ianwensink Sounds good!

So a thing I'm still wondering about is blocks being passed to the frontend. We have on our website blocks defined in `/admin/structure/block` and they are limited on the frontpage. However when I have my `node__article: NodeArticle` component and I am logging the `props.entity` I can see no blocks or what so ever. 

Is this still a feature that has to be implemented? Or is this already implemented?

Also, when I am logging `props` in a component then it shows `{ entity: { ... }, page: { ... }, paragraph: { ... } }` where all the object are the same. Is this still under development as well? For now I always grab the `props.entity`.

**Comment by ianwensink** [comment]
Hi kkoomen,

We’ve never implemented blocks since we don’t use them ourselves. I have some vague memory of Bart talking about this. If I’m correct, blocks are configuration entities and are therefore perhaps selectable through the HN Config module? I will check and come back on that later. 

About the props: this is all for backwards compatibility. We are of course using HN in most of our projects while still developing it. We don’t want to break those older projects, so that’s why. 

The entity prop is the right one, you should indeed use that to stay ahead of depreciation. The page props is only there on entities mapped by the DrupalPage and is therefore probably going to stay, but if you use entity you should be fine either way.

**Comment by kkoomen** [comment]
@ianwensink Ahh, cool :)

If you could help me with the HN config, yes please. I've enabled the "blocks" in the `restui` module, but it doesn't appear at the HN config. If you could answer that, that'd be great :)
